=== making/yuimarl/yuimarl-test-mysql/yuimarl.dtd
<!ELEMENT dataset (
    CORPORATION*,
    EVENT*,
    EVENTSET*,
    EVENTVIEW*,
    EVENTVIEWSET*,
    EVENTVIEW_SPREAD*,
    GENERATED_ID*,
    GOODS*,
    GOODS_CATEGORY*,
    ORGANIZATION*,
    ORG_CATEGORY*,
    PARTY*,
    PARTY_RELATION*,
    PERSON*,
    PREFECTURE*,
    YUIMARL_USER*)>

<!ELEMENT CORPORATION EMPTY>
<!ATTLIST CORPORATION
    PARTY_NO CDATA #REQUIRED
    URL CDATA #IMPLIED
    CAPITAL CDATA #IMPLIED
    ACCOUNT_MONTH CDATA #IMPLIED
>

<!ELEMENT EVENT EMPTY>
<!ATTLIST EVENT
    EVENT_NO CDATA #REQUIRED
    EVENTSET_NO CDATA #IMPLIED
    EVENT_CLASS CDATA #IMPLIED
    EVENT_TYPE CDATA #IMPLIED
    NAME CDATA #IMPLIED
    TERM_FROM CDATA #IMPLIED
    TERM_TO CDATA #IMPLIED
    START_TIME CDATA #IMPLIED
    END_TIME CDATA #IMPLIED
    PLACE CDATA #IMPLIED
    AFFILIATE CDATA #IMPLIED
    SUNDAY CDATA #IMPLIED
    MONDAY CDATA #IMPLIED
    TUESDAY CDATA #IMPLIED
    WEDNESDAY CDATA #IMPLIED
    THURSDAY CDATA #IMPLIED
    FRIDAY CDATA #IMPLIED
    SATURDAY CDATA #IMPLIED
    HOLIDAY CDATA #IMPLIED
    EXCEPT_MOVE CDATA #IMPLIED
    INVALID_MOVE CDATA #IMPLIED
    INCLUDE_DAYS CDATA #IMPLIED
    EXCLUDE_DAYS CDATA #IMPLIED
    OPEN_OTHERS CDATA #IMPLIED
    COLOR CDATA #IMPLIED
    MEMO CDATA #IMPLIED
    REP_INTERVAL CDATA #IMPLIED
    REP_DAY CDATA #IMPLIED
    REP_WEEK CDATA #IMPLIED
    REP_MONTH CDATA #IMPLIED
    LABEL CDATA #IMPLIED
    LABEL_START CDATA #IMPLIED
    ACTUAL_FROM CDATA #IMPLIED
    ACTUAL_TO CDATA #IMPLIED
    DAY_COUNT CDATA #IMPLIED
    PRE_TASK CDATA #IMPLIED
    PROGRESS CDATA #IMPLIED
    FINISHED CDATA #IMPLIED
    DEL_FLG CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

<!ELEMENT EVENTSET EMPTY>
<!ATTLIST EVENTSET
    EVENTSET_NO CDATA #REQUIRED
    NAME CDATA #IMPLIED
    OWNER CDATA #IMPLIED
    DEL_FLG CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

<!ELEMENT EVENTVIEW EMPTY>
<!ATTLIST EVENTVIEW
    EVENTVIEW_NO CDATA #REQUIRED
    OWNER CDATA #IMPLIED
    NAME CDATA #IMPLIED
    SEQ CDATA #IMPLIED
    JAPANESE_HOLIDAY CDATA #IMPLIED
    SPREAD_YEARS CDATA #IMPLIED
    DEL_FLG CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

<!ELEMENT EVENTVIEWSET EMPTY>
<!ATTLIST EVENTVIEWSET
    EVENTVIEW CDATA #REQUIRED
    EVENTSET CDATA #REQUIRED
    AUTH_OWNER CDATA #IMPLIED
    AUTH_UPDATE CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

<!ELEMENT EVENTVIEW_SPREAD EMPTY>
<!ATTLIST EVENTVIEW_SPREAD
    EVENTVIEW_NO CDATA #REQUIRED
    SPREAD_DATE CDATA #REQUIRED
    EVENTSET_NO CDATA #REQUIRED
    EVENT_NO CDATA #REQUIRED
    START_TIME CDATA #IMPLIED
    END_TIME CDATA #IMPLIED
    EVENT_CLASS CDATA #IMPLIED
    EVENT_TYPE CDATA #IMPLIED
    NAME CDATA #IMPLIED
    EVENT_TERM CDATA #IMPLIED
    COLOR CDATA #IMPLIED
>

<!ELEMENT GENERATED_ID EMPTY>
<!ATTLIST GENERATED_ID
    KEY_NAME CDATA #REQUIRED
    VALUE CDATA #REQUIRED
>

<!ELEMENT GOODS EMPTY>
<!ATTLIST GOODS
    PARTY_NO CDATA #REQUIRED
    CATEGORY_NO CDATA #IMPLIED
>

<!ELEMENT GOODS_CATEGORY EMPTY>
<!ATTLIST GOODS_CATEGORY
    CATEGORY_NO CDATA #REQUIRED
    NAME CDATA #IMPLIED
    NAME_KANA CDATA #IMPLIED
    PARENT_CATEGORY CDATA #IMPLIED
    DEL_FLG CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

<!ELEMENT ORGANIZATION EMPTY>
<!ATTLIST ORGANIZATION
    PARTY_NO CDATA #REQUIRED
    CATEGORY CDATA #IMPLIED
    PERSON_COUNT CDATA #IMPLIED
>

<!ELEMENT ORG_CATEGORY EMPTY>
<!ATTLIST ORG_CATEGORY
    CATEGORY_NO CDATA #REQUIRED
    NAME CDATA #REQUIRED
    PARTY_TYPE CDATA #REQUIRED
    DEL_FLG CDATA #IMPLIED
>

<!ELEMENT PARTY EMPTY>
<!ATTLIST PARTY
    PARTY_NO CDATA #REQUIRED
    PARTY_TYPE CDATA #REQUIRED
    NAME CDATA #IMPLIED
    NAME_KANA CDATA #IMPLIED
    ZIP_CODE CDATA #IMPLIED
    PREFECTURE CDATA #IMPLIED
    CITY CDATA #IMPLIED
    ADDRESS1 CDATA #IMPLIED
    ADDRESS2 CDATA #IMPLIED
    PHONE_NO CDATA #IMPLIED
    FAX_NO CDATA #IMPLIED
    MAIL_ADDRESS1 CDATA #IMPLIED
    MAIL_ADDRESS2 CDATA #IMPLIED
    START_DATE CDATA #IMPLIED
    END_DATE CDATA #IMPLIED
    MEMO CDATA #IMPLIED
    DEL_FLG CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

<!ELEMENT PARTY_RELATION EMPTY>
<!ATTLIST PARTY_RELATION
    RELATION_NO CDATA #REQUIRED
    RELATION_TYPE CDATA #IMPLIED
    PARTY1 CDATA #IMPLIED
    ROLE1 CDATA #IMPLIED
    PARTY2 CDATA #IMPLIED
    ROLE2 CDATA #IMPLIED
    TERM_FROM CDATA #IMPLIED
    TERM_TO CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

<!ELEMENT PERSON EMPTY>
<!ATTLIST PERSON
    PARTY_NO CDATA #REQUIRED
    LAST_NAME CDATA #IMPLIED
    FIRST_NAME CDATA #IMPLIED
    LAST_NAME_KANA CDATA #IMPLIED
    FIRST_NAME_KANA CDATA #IMPLIED
    GENDER CDATA #IMPLIED
    CELL_PHONE_NUMBER CDATA #IMPLIED
>

<!ELEMENT PREFECTURE EMPTY>
<!ATTLIST PREFECTURE
    PREFECTURE_NO CDATA #REQUIRED
    NAME CDATA #IMPLIED
    DEL_FLG CDATA #IMPLIED
>

<!ELEMENT YUIMARL_USER EMPTY>
<!ATTLIST YUIMARL_USER
    USER_NO CDATA #REQUIRED
    USER_ID CDATA #IMPLIED
    PASSWORD CDATA #REQUIRED
    PARTY CDATA #IMPLIED
    DEL_FLG CDATA #IMPLIED
    REGIST_USER CDATA #IMPLIED
    REGIST_TIME CDATA #IMPLIED
    UPDATE_USER CDATA #IMPLIED
    UPDATE_TIME CDATA #IMPLIED
    AUTH_MAP CDATA #IMPLIED
    AUTH_REGIST_USER CDATA #IMPLIED
    AUTH_REGIST_TIME CDATA #IMPLIED
    AUTH_UPDATE_USER CDATA #IMPLIED
    AUTH_UPDATE_TIME CDATA #IMPLIED
    VERSION_NO CDATA #IMPLIED
>

=== making/yuimarl/yuimarl-test-javadb/xml/expectedDataSet1.xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE dataset SYSTEM "yuimarl.dtd">
<dataset>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140101" EVENTSET_NO="1" EVENT_NO="1" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="1" NAME="元日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140107" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140113" EVENTSET_NO="1" EVENT_NO="12" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="3" NAME="成人の日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140114" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140115" EVENTSET_NO="2" EVENT_NO="102" START_TIME="1400" END_TIME="1530" EVENT_CLASS="2" EVENT_TYPE="0" NAME="会議2" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140121" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140127" EVENTSET_NO="2" EVENT_NO="108" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140128" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140131" EVENTSET_NO="2" EVENT_NO="110" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly2" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140204" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140211" EVENTSET_NO="1" EVENT_NO="2" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="1" NAME="建国記念の日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140212" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140212" EVENTSET_NO="2" EVENT_NO="111" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="12" NAME="Monthly3" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140215" EVENTSET_NO="2" EVENT_NO="103" START_TIME="1400" END_TIME="1530" EVENT_CLASS="2" EVENT_TYPE="0" NAME="会議3" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140218" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140220" EVENTSET_NO="2" EVENT_NO="114" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="6" NAME="誕生日(49才)" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140225" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140228" EVENTSET_NO="2" EVENT_NO="110" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly2" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140303" EVENTSET_NO="1" EVENT_NO="18" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="6" NAME="ひな祭り" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140305" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140311" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140318" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140321" EVENTSET_NO="1" EVENT_NO="16" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="2" NAME="春分の日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140325" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140325" EVENTSET_NO="2" EVENT_NO="108" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140331" EVENTSET_NO="2" EVENT_NO="110" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly2" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140401" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140408" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140415" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140422" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140429" EVENTSET_NO="1" EVENT_NO="4" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="1" NAME="昭和の日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140430" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140430" EVENTSET_NO="2" EVENT_NO="110" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly2" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140503" EVENTSET_NO="1" EVENT_NO="5" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="1" NAME="憲法記念日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140504" EVENTSET_NO="1" EVENT_NO="7" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="1" NAME="みどりの日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140505" EVENTSET_NO="1" EVENT_NO="8" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="1" NAME="こどもの日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140506" EVENTSET_NO="1" EVENT_NO="0" START_TIME=" " END_TIME=" " EVENT_CLASS="2" EVENT_TYPE="5" NAME="振替休日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140507" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140511" EVENTSET_NO="1" EVENT_NO="21" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="7" NAME="母の日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140513" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140513" EVENTSET_NO="2" EVENT_NO="111" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="12" NAME="Monthly3" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140520" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140526" EVENTSET_NO="2" EVENT_NO="108" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140527" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140531" EVENTSET_NO="2" EVENT_NO="110" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly2" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140603" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140610" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140615" EVENTSET_NO="1" EVENT_NO="22" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="7" NAME="父の日" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140617" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140624" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140630" EVENTSET_NO="2" EVENT_NO="110" START_TIME="0615" END_TIME="1200" EVENT_CLASS="5" EVENT_TYPE="11" NAME="Monthly2" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140701" EVENTSET_NO="2" EVENT_NO="106" START_TIME="1400" END_TIME="1530" EVENT_CLASS="4" EVENT_TYPE="0" NAME="Weekly1" EVENT_TERM="0"/>
  <EVENTVIEW_SPREAD EVENTVIEW_NO="1" SPREAD_DATE="20140707" EVENTSET_NO="1" EVENT_NO="19" START_TIME=" " END_TIME=" " EVENT_CLASS="1" EVENT_TYPE="6" NAME="七夕" EVENT_TERM="0"/>
